### ISSUE TITLE
ngo-profile | identifier not mandatory

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#189] opened 2016-09-14 14:29 UTC
The identifier should not be mandatory, as there will be "private" organisations that may not have an ID.

**Comment by votexx** [comment] 2016-09-15 17:12
I´m sorry...not even not mandatory -> we don´t need it at all (just causing problems with registration and authorities).

So ID can be deleted/deactivated completely.

**Comment by haslinger** [comment] 2016-09-15 17:28
Reopening is fine in such a case. -> So the full dialog is available without switching between tickets.
Another example: We had a misunderstanding and we closed the ticket, but the issue is not resolved ...

**Comment by klappradla** [comment] 2016-09-16 20:16
Remove special identifier column from NGO/contact model.

**Comment by ramonh** [comment] 2016-09-28 18:47
Should be fixed as of 2286803

**Closed by ramonh** 2016-09-28 18:47 UTC
Labels: datamodel
