### ISSUE TITLE
creating event -> error-page

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#180] opened 2016-08-18 11:18 UTC
I tried to create a new event right now for today and got the following error-message:
![w2h_error_new event_20160818](https://cloud.githubusercontent.com/assets/19605344/17771858/d9ea680e-6545-11e6-9bc4-03d09254e4fb.PNG)

I went back (browser-button) and got an error saying "Adresse muss ausgefüllt werden" - I did, though. I think there was an adress-sugestion before, which there isn´t any longer.

Michael is planning to present the app today (2pm :-) - your help is very much appreciated

**Comment by haslinger** [comment] 2016-08-19 06:41
Ok, there is an regression in the progressbar, not yet fully understood.

**Comment by haslinger** [comment] 2016-08-19 06:51
Meanwhile I know, why autocompletion is not working any more.
Heroku switched to https while we try to acquire data via http, which modern browsers do not allow any more, when the orig page has been loaded via https.
So I switched to get autocompletion data via https always and that part of the issue is resolved.

**Comment by haslinger** [comment] 2016-08-19 07:00
The progressbar was invoked in the old way (in it still is in other views).
I believe, I fixed it correctly with ed2a31a75e868, but I'm not sure about the other locations. 
So please @klappradla have a look at the views calling it in the old fashion before we finally close this issue.

**Closed** 2016-08-24 19:26 UTC
Labels: bug

**Comment by klappradla** [comment] 2016-08-24 19:31
Thanx for pointing this out @haslinger !
Should be fixed now. https://github.com/where2help/where2help/commit/c85deae57d96ddf62e4c4dafbcd35d049ad390c3 is what introduces the big difference: if an event doesn't have **any** available shifts any more, I return the numbers for all its shifts *(instead of nil)*. This allows us to also display progress bars for past events (looking at the spec file will make it clear 😉 )
